### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
np.array([1,2,3])

In [ ]:
import numpy as np

In [ ]:
import sys
sys.getsizeof(list123)

88

In [ ]:
a = np.array(list123,dtype=np.int64)

In [ ]:
sys.getsizeof(a)

136

In [ ]:
list123= [199,200,201]
type(list123)

list

In [ ]:
list1=np.array([1,2,3,4],dtype=np.int8)
list1.dtype

dtype('int8')

In [ ]:
# 2D and 3D
b = np.array(list123)
print(b)
b.dtype

[199 200 201]


dtype('int64')

In [ ]:
c = np.array([[[301,301],[3,4]],[[5,6],[7,8]]]).ravel()

print(c)
c.dtype

[301 301   3   4   5   6   7   8]


dtype('int64')

In [ ]:
c2 = np.array([[[301,301],[3,4]],[[5,6],[7,8]]]).flatten()
print(c2)

[301 301   3   4   5   6   7   8]


In [ ]:
# dtype
c = np.array([1,2,3],dtype=float)

print(c)
print(c.dtype)
sys.getsizeof(c)

[1. 2. 3.]
float64


136

In [ ]:
# np.arange
np.arange(100,111,1)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
# with reshape
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# with reshape
np.arange(301,311).reshape(2,5)

array([[301, 302, 303, 304, 305],
       [306, 307, 308, 309, 310]])

In [ ]:
# np.ones and np.zero
np.zeros([4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((1,100))

array([0.11307385, 0.39485886, 0.90302539, 0.81689701, 0.87058873,
       0.46226456, 0.08904056, 0.36412357, 0.32539107, 0.02316852,
       0.42329694, 0.94014257, 0.6598873 , 0.33733644, 0.12236288,
       0.17556333, 0.45730517, 0.79292846, 0.18558745, 0.89875166,
       0.71517751, 0.55083143, 0.26075617, 0.94054177, 0.73732887,
       0.02506608, 0.18197684, 0.77415258, 0.71835998, 0.89468533,
       0.82638735, 0.87521273, 0.70722011, 0.25968098, 0.06411894,
       0.86580437, 0.69746727, 0.48671124, 0.44414492, 0.82926188,
       0.8489313 , 0.60643003, 0.5979544 , 0.05968332, 0.56925017,
       0.1375982 , 0.57278188, 0.28753846, 0.35552753, 0.19983918,
       0.65776051, 0.81143322, 0.59093436, 0.55234879, 0.25804955,
       0.69359715, 0.78630579, 0.14216697, 0.10540519, 0.46174125,
       0.73685967, 0.91137601, 0.52999291, 0.6128317 , 0.58144831,
       0.61106036, 0.13464149, 0.27315381, 0.89641759, 0.2135951 ,
       0.45057377, 0.49044339, 0.97297337, 0.71207627, 0.72331

In [ ]:
# np.linspace
np.linspace(1,10,3,dtype=int)

array([ 1,  5, 10])

In [ ]:
# np.identity
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a2.ndim

2

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize

print(a3.itemsize)
print(a3.size)
a3

8
8


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int64
int64


In [ ]:
a1 = np.arange(9).reshape(3,3)
a2 = np.array([[5,5,5],[5,5,5],[5,5,5]]).reshape(3,3)

In [ ]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
a1 + 5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
a1 + a2

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
a1 = np.array([1,2,3,4]).reshape(2,2)
a1

array([[1, 2],
       [3, 4]])

In [ ]:
a2 = np.array([5,5,5,5]).reshape(2,2)
a2

array([[5, 5],
       [5, 5]])

In [ ]:
a1 * 5

array([[ 5, 10],
       [15, 20]])

In [ ]:
a1 * a2

array([[ 5, 10],
       [15, 20]])

### Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(100).reshape(2,50)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [ ]:
# scalar operations

# arithmetic
a1 * 2

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
         52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
         78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
        126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
        152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
        178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [ ]:
# relational
a1 == 1

array([[ True, False],
       [False, False]])

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[74., 88., 83.],
       [72., 47., 97.],
       [39., 34., 47.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1)

0

In [ ]:
a1 = [1,2,3,4]
a2 = [4,1,2,3]
x = np.array(a1)
y = np.array(a2)

In [ ]:
x * y

array([ 4,  2,  6, 12])

In [ ]:
np.max(a1,axis=1)

array([ 2,  5,  8, 11])

In [ ]:
np.max(a1,axis=0)

array([ 9, 10, 11])

In [ ]:
# mean/median/std/var
np.std(a1,axis=1)

array([ 5.79271573, 20.41241452,  5.35412613])

In [ ]:
# trigonomoetric functions
np.tan(a1)

array([[-5.73702254,  0.0354205 ,  3.88059631],
       [-0.26241738, -0.12452757, -0.4103213 ],
       [ 3.61455441, -0.62349896, -0.12452757]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

In [ ]:
# round/floor/ceil

mann = (np.random.random((2,3))*100)

In [ ]:
mann

array([[79.22322387, 41.38187102, 96.69101594],
       [64.37983521, 38.15430748, 21.94599585]])

In [ ]:
np.ceil(mann)

array([[80., 42., 97.],
       [65., 39., 22.]])

In [ ]:
np.floor(mann)

array([[79., 41., 96.],
       [64., 38., 21.]])

In [ ]:
np.round(mann)

array([[79., 41., 97.],
       [64., 38., 22.]])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[2,2]

10

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
anand = np.arange(12).reshape(3,4)
anand

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Iterating

In [ ]:
for mann in np.nditer(anand):
  print(mann)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
bharat = np.vstack((a4,a5))
bharat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting
np.hsplit(bharat,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [ ]:
# vertical splitting
np.vsplit(bharat,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]